name = "tentrait-app"
compatibility_date = "2024-05-30"
compatibility_flags = ["nodejs_compat"]

main = "src/entry-server.ts"  # default for SvelteKit if not using Vite adapter
build.command = "npm run build"

[site]
bucket = "./.svelte-kit/cloudflare"
entry-point = "."

[vars]
TURNSTILE_SECRET = "0x4AAAAAABfTUEon56iJ_QCRiG-Y0U-Y2cg"

[[r2_buckets]]
binding = "TENTRAIT_UPLOADS"
bucket_name = "tentrait-pcap"

[[kv_namespaces]]
binding = "TENTRAIT_KV"
id = "your_kv_namespace_id"             # from `wrangler kv:namespace list`
preview_id = "your_kv_preview_namespace_id"  # optional for `wrangler dev`

[[queues.producers]]
binding = "TENTRAIT_ANALYSIS_QUEUE"
queue = "analysis-queue"

[[queues.consumers]]
queue = "analysis-queue"
consumer_script = "analysis-worker"

[env.production]
name = "tentrait-app"
route = "https://tentrait.com/*"
